# Generated by Django 5.1.1 on 2024-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Chairperson', 'Chairperson')], max_length=20)),
                ('entry_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('September', 'September')], max_length=20)),
                ('entry_year', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
