# Generated by Django 5.1.1 on 2024-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_memberregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='entry_month',
            field=models.CharField(max_length=20),
        ),
    ]
